library(Seurat)
library(future)
load('janssen_seurat.Rda')
celltype <- levels(dn.integrated)
### 1. get all DEG lists for the day2 treatment timepoint ####
day2<-SetIdent(dn.integrated, value="group")
day2<-subset(day2, idents=c("Grp1","Grp3a","Grp4a","Grp5a","Grp6a","Grp7a","Grp8a"))
day2<-SetIdent(day2, value="celltype")
options(future.globals.maxSize = 8000 * 1024^2)
plan("multiprocess", workers = 10)
for (i in 1:length(celltype)){
  cell1<-subset(day2, idents=celltype[i])
  cell1<-SetIdent(cell1, value='group')
  markers1<-FindMarkers(cell1, ident.1 = 'Grp3a', ident.2 = 'Grp1',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '1', 'day2'))
  markers2<-FindMarkers(cell1, ident.1 = 'Grp4a', ident.2 = 'Grp3a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '2', 'day2'))
  markers3<-FindMarkers(cell1, ident.1 = 'Grp5a', ident.2 = 'Grp3a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '3', 'day2'))
  markers4<-FindMarkers(cell1, ident.1 = 'Grp6a', ident.2 = 'Grp3a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '4', 'day2'))
  markers5<-FindMarkers(cell1, ident.1 = 'Grp7a', ident.2 = 'Grp3a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '5', 'day2'))
  markers6<-FindMarkers(cell1, ident.1 = 'Grp8a', ident.2 = 'Grp3a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '6', 'day2'))
  markers7<-FindMarkers(cell1, ident.1 = 'Grp8a', ident.2 = 'Grp4a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '7', 'day2'))
  markers8<-FindMarkers(cell1, ident.1 = 'Grp8a', ident.2 = 'Grp7a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '8', 'day2'))
  markers9<-FindMarkers(cell1, ident.1 = 'Grp6a', ident.2 = 'Grp4a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '9', 'day2'))
  markers10<-FindMarkers(cell1, ident.1 = 'Grp6a', ident.2 = 'Grp5a',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '10', 'day2'))
  cell1_deg<-list(markers1, markers2,markers3,markers4,markers5,markers6,markers7,markers8,markers9,markers10)
  save(cell1_deg, file = paste0(celltype[i],"_day2",'_deg.Rda'))
  print(paste(celltype[i], 'day2', 'all done!'))
}
print('All done!')

### 2. get all DEG lists for the week2 treatment timepoint ####
week2<-SetIdent(dn.integrated, value="group")
week2<-subset(week2, idents=c("Grp1","Grp3b","Grp4b","Grp5b","Grp6b","Grp7b","Grp8b"))
week2<-SetIdent(week2, value="celltype")
options(future.globals.maxSize = 8000 * 1024^2)
plan("multiprocess", workers = 10)
for (i in 1:length(celltype)){
  cell1<-subset(week2, idents=celltype[i])
  cell1<-SetIdent(cell1, value='group')
  markers1<-FindMarkers(cell1, ident.1 = 'Grp3b', ident.2 = 'Grp1',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '1', 'week2'))
  markers2<-FindMarkers(cell1, ident.1 = 'Grp4b', ident.2 = 'Grp3b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '2', 'week2'))
  markers3<-FindMarkers(cell1, ident.1 = 'Grp5b', ident.2 = 'Grp3b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '3', 'week2'))
  markers4<-FindMarkers(cell1, ident.1 = 'Grp6b', ident.2 = 'Grp3b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '4', 'week2'))
  markers5<-FindMarkers(cell1, ident.1 = 'Grp7b', ident.2 = 'Grp3b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '5', 'week2'))
  markers6<-FindMarkers(cell1, ident.1 = 'Grp8b', ident.2 = 'Grp3b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '6', 'week2'))
  markers7<-FindMarkers(cell1, ident.1 = 'Grp8b', ident.2 = 'Grp4b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '7', 'week2'))
  markers8<-FindMarkers(cell1, ident.1 = 'Grp8b', ident.2 = 'Grp7b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '8', 'week2'))
  markers9<-FindMarkers(cell1, ident.1 = 'Grp6b', ident.2 = 'Grp4b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '9', 'week2'))
  markers10<-FindMarkers(cell1, ident.1 = 'Grp6b', ident.2 = 'Grp5b',only.pos = F, logfc.threshold = 0.25, min.pct = 0.1)
  print(paste(celltype[i], '10', 'week2'))
  cell1_deg<-list(markers1, markers2,markers3,markers4,markers5,markers6,markers7,markers8,markers9,markers10)
  save(cell1_deg, file = paste0(celltype[i],"_week2",'_deg.Rda'))
  print(paste(celltype[i], 'week2', 'all done!'))
}
print('All done!')


