#### Integration analysis ####
setwd('/mnt/sdc/Janssen_newProcessing/input')
library(Matrix)
library(ggplot2)
library(Seurat)
library(stringr)
Sys.time()
all_rds<-list.files()
dn.list<-list()
for (i in 1:length(all_rds)){
  dn.list[[i]]<-readRDS(all_rds[i])
  print(i)
}
names(dn.list)<-str_extract(all_rds, "[^_]+")
dn.features <- SelectIntegrationFeatures(object.list = dn.list, nfeatures = 1500)
dn.list <- PrepSCTIntegration(object.list = dn.list, anchor.features = dn.features)
reference_dataset <- which(names(dn.list) == "A3020")
dn.anchors <- FindIntegrationAnchors(object.list = dn.list,
                                       anchor.features = dn.features, reference = reference_dataset, 
                                       normalization.method = "SCT")
Sys.time()
print('FindAnchor done!')
dn.integrated <- IntegrateData(anchorset = dn.anchors, normalization.method = "SCT")
print('Integration done!')
Sys.time()
dn.integrated <- RunPCA(object = dn.integrated, npcs = 100)
print('RunPCA done!')
dn.integrated <- RunUMAP(object = dn.integrated, dims = 1:30)
print('RunUMAP done!')
dn.integrated <- FindClusters(dn.integrated, resolution = 0.3)
print('FindCluster done!')
save(dn.integrated, file = 'janssen_seurat.Rda')
print("Clustering done!")
Sys.time()
