data_processing<-function(cellbender_h5, sampleID, out_dir){
new_df<-Read10X_h5(cellbender_h5)
colnames(new_df)<-paste(sampleID, colnames(new_df), sep="_")
##### 1.initial QC and clustering ####
Sample4<- CreateSeuratObject(counts = new_df, project = sampleID, min.cells = 3, min.features = 200)
metadata<-Sample4@meta.data
png(paste0(out_dir,sampleID, "_counts_histogram_before_clean.png"), units="in", width=6, height=4, res=300)
hist(
  metadata$nFeature_RNA,
  breaks = 1000
)
dev.off()
Sample4[["percent.mt"]] <- PercentageFeatureSet(Sample4, pattern = "^mt-")
png(paste0(out_dir,sampleID, "_counts_QC_before_clean.png"), units="in", width=8, height=4, res=300)
print(VlnPlot(Sample4, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1))
dev.off()
Sample4<- subset(Sample4, subset = nFeature_RNA > 500 & nFeature_RNA < 6000 & percent.mt < 5)
Sample4<- NormalizeData(Sample4)
Sample4<- FindVariableFeatures(Sample4, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(Sample4)
Sample4<- ScaleData(Sample4, features = all.genes)
Sample4<- RunPCA(Sample4, features = VariableFeatures(object = Sample4), npcs = 50)
png(paste0(out_dir,sampleID, "_PCA_elbowplot_before_clean.png"), units="in", width=6, height=4, res=300)
print(ElbowPlot(Sample4, ndims = 50))
dev.off()
Sample4<- FindNeighbors(Sample4, dims = 1:30)
Sample4<- FindClusters(Sample4, resolution = 0.5)
Sample4<- RunUMAP(Sample4, dims = 1:30)
Sample4<-SubsetData(Sample4, ident.remove = 0)
Sample4<- CreateSeuratObject(counts = Sample4@assays$RNA@counts, project = sampleID, min.cells = 3, min.features = 200)
Sample4
metadata<-Sample4@meta.data
png(paste0(out_dir,sampleID, "_counts_histogram_before_clean.png"), units="in", width=6, height=4, res=300)
hist(
  metadata$nFeature_RNA,
  breaks = 1000
)
dev.off()
Sample4[["percent.mt"]] <- PercentageFeatureSet(Sample4, pattern = "^mt-")
png(paste0(out_dir,sampleID, "_counts_QC_before_clean.png"), units="in", width=8, height=4, res=300)
print(VlnPlot(Sample4, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1))
dev.off()
Sample4<- NormalizeData(Sample4)
Sample4<- FindVariableFeatures(Sample4, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(Sample4)
Sample4<- ScaleData(Sample4, features = all.genes)
Sample4<- RunPCA(Sample4, features = VariableFeatures(object = Sample4), npcs = 50)
png(paste0(out_dir,sampleID, "_PCA_elbowplot_before_clean.png"), units="in", width=6, height=4, res=300)
print(ElbowPlot(Sample4, ndims = 50))
dev.off()
Sample4<- FindNeighbors(Sample4, dims = 1:30)
Sample4<- FindClusters(Sample4, resolution = 0.5)
Sample4<- RunUMAP(Sample4, dims = 1:30)
Sample4<-RunTSNE(Sample4, dims = 1:30, perplexity=50)
png(paste0(out_dir,sampleID, "_UMAP_before_clean.png"), units="in", width=6, height=4, res=300)
print(DimPlot(Sample4, reduction = "umap"))
dev.off()
png(paste0(out_dir,sampleID, "_tSNE_before_clean.png"), units="in", width=6, height=4, res=300)
print(DimPlot(Sample4, reduction = "tsne"))
dev.off()
png(paste0(out_dir,sampleID, "_markers_before_clean.png"), units="in", width=15, height=15, res=300)
print(FeaturePlot(Sample4, features = c('Nphs1','Slc5a12',"Slc7a12",'Slc12a1',"Slc12a3","Emcn",'Fhl2',"Tnc","Aqp2","Ptprc","Slc26a4",'Kit'), reduction = 'tsne'))
dev.off()
png(paste0(out_dir,sampleID, "_nGene_tSNE_before_clean.png"), units="in", width=6, height=4, res=300)
print(FeaturePlot(Sample4, features = "nFeature_RNA", reduction = 'tsne'))
dev.off()
saveRDS(Sample4, file = paste0(out_dir,sampleID,'_seurat.rds'))
Sys.time()
print(paste(sampleID,"initial clustering done!", sep = ":"))

### 2.doubleFinder to remove doublets ###
doublet_rate<-0.018+8.4e-06*ncol(Sample4)  ##This function is based on the data from the Demuxlet paper##
ndoublets<-doublet_rate*ncol(Sample4)
Sample4<-doubletFinder_v3(Sample4,PCs = 1:30, nExp = ndoublets, pK = 0.09)
png(paste0(out_dir,sampleID, "_doublets_tSNE.png"), units="in", width=6, height=4, res=300)
print(TSNEPlot(Sample4, group.by=paste0('DF.classifications_0.25_0.09_', ndoublets)))
dev.off()
Sample4<-SetIdent(Sample4, value = paste0('DF.classifications_0.25_0.09_', ndoublets))
Sample4_clean<-subset(Sample4, idents = 'Singlet')
Sys.time()
print(paste(sampleID,"doubletFinder done!", sep = ":"))

### 3.recluster the singlets ####
Sample4_clean <- CreateSeuratObject(counts = Sample4_clean@assays$RNA@counts, project = sampleID, min.cells = 3, min.features = 200)
Sample4_clean
metadata<-Sample4_clean@meta.data
png(paste0(out_dir,sampleID, "_counts_histogram_after_clean.png"), units="in", width=6, height=4, res=300)
hist(
  metadata$nFeature_RNA,
  breaks = 1000
)
dev.off()
Sample4_clean[["percent.mt"]] <- PercentageFeatureSet(Sample4_clean, pattern = "^mt-")
png(paste0(out_dir,sampleID, "_counts_QC_after_clean.png"), units="in", width=8, height=4, res=300)
print(VlnPlot(Sample4_clean, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0.1))
dev.off()
Sample4_clean <- NormalizeData(Sample4_clean)
Sample4_clean <- FindVariableFeatures(Sample4_clean, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(Sample4_clean)
Sample4_clean <- ScaleData(Sample4_clean, features = all.genes)
Sample4_clean <- RunPCA(Sample4_clean, features = VariableFeatures(object = Sample4_clean), npcs = 50)
png(paste0(out_dir,sampleID, "_PCA_elbowplot_after_clean.png"), units="in", width=6, height=4, res=300)
print(ElbowPlot(Sample4_clean, ndims = 50))
dev.off()
Sample4_clean <- FindNeighbors(Sample4_clean, dims = 1:25)
Sample4_clean <- FindClusters(Sample4_clean, resolution = 0.6)
Sample4_clean <- RunUMAP(Sample4_clean, dims = 1:25, min.dist = 0.6, spread = 3)
print(paste(sampleID,"final clustering done!", sep = ":"))
png(paste0(out_dir,sampleID, "_UMAP_after_clean.png"), units="in", width=6, height=4, res=300)
print(DimPlot(Sample4_clean, reduction = "umap", label = T))
dev.off()
png(paste0(out_dir,sampleID, "_markers_after_clean.png"), units="in", width=15, height=15, res=300)
print(FeaturePlot(Sample4_clean, features = c('Nphs1','Slc5a12',"Slc7a12",'Slc12a1',"Slc12a3","Emcn",'Fhl2',"Tnc","Aqp2","Ptprc","Slc26a4",'Kit')))
dev.off()
png(paste0(out_dir,sampleID, "_nGene_UMAP_after_clean.png"), units="in", width=6, height=4, res=300)
print(FeaturePlot(Sample4_clean, features = 'nFeature_RNA'))
dev.off()
saveRDS(Sample4_clean, file=paste0(out_dir,sampleID,'_seurat_clean.rds'))
library(loomR)
pfile <- create( filename = paste0(out_dir,sampleID,'.loom'),data = Sample4_clean@assays$RNA@counts)
pfile$close_all()
print(paste(sampleID,"all done!", sep = ":"))
Sys.time()
}
